apiVersion: v1
kind: Service
metadata:
  labels:
    name: node
    role: service
  name: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    grafana: "true"
