apiVersion: v1
kind: Service
metadata:
  name: sample-web-service 
  labels:
    app: sample-web-service 
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 80 
  selector:
    app: sample-web-service
